version: "3.9"
services:
  raiko:
    image: gcr.io/evmchain/raiko:latest-pos
    container_name: raiko
    command: --config-path=/etc/opt/raiko/config/config.toml
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - /tmp/sgx:/tmp/sgx
      - /var/log/raiko:/var/log/raiko
      # - YOUR_CONFIG_PATH:/etc/opt/raiko/config.toml
      - ${HOME}/.config/raiko:/etc/opt/raiko
    ports:
      - "8080:8080"
